# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: ChiefMedicalOfficer
  name: job-name-cmo
  description: job-description-cmo
  playTimeTracker: JobChiefMedicalOfficer
  requirements:
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 2.5h
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 5h
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 10h
    - !type:RoleTimeRequirement  # CorvaxGoob
      role: JobSurgeon
      time: 2h # CorvaxGoob
    - !type:SpeciesRequirement # Goob - None Felinid
      inverted: true
      species:
      - Felinid
    - !type:SpeciesRequirement # CorvaxGoob-Species
      inverted: true
      species:
      - Abductor
  weight: 10
  startingGear: CMOGear
  icon: "JobIconChiefMedicalOfficer"
  supervisors: job-supervisors-captain
  canBeAntag: false
  skills: # CorvaxGoob-Skills
  - Surgery
  - MedicalEquipment
  guides: # goobstation
  - Medical
  # - ChiefMedicalOfficer SOP Hidden by CorvaxGoob
  # - Medical SOP Hidden by CorvaxGoob
  - Command
  - Chemicals
  - Virology
  #goobcoins: 40 #Goob content Corvax-Goob-coins
  access:
  - Medical
  - Command
  - Maintenance
  - Chemistry
  - ChiefMedicalOfficer
  - Brig
  - Cryogenics
  - External # goobstation
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  # Shitmed Change
  - !type:AddComponentSpecial
    components:
    - type: SurgerySpeedModifier
      speedModifier: 2

- type: startingGear
  id: CMOGear
  equipment:
    id: CMOPDA
    ears: ClothingHeadsetAltMedical # Goobstation
#   eyes: ClothingEyesGlassesMed # Goobstation # CorvaxGoob-loadouts: replaced on a ChiefMedicalOfficerGlasses loadout
    belt: ClothingBeltMedicalFilled
  storage:
    back:
    - Flash
    - TelescopicBaton # Goobstation

- type: chameleonOutfit
  id: ChiefMedicalOfficerChameleonOutfit
  job: ChiefMedicalOfficer
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretCmo
    eyes: ClothingEyesGlassesMedChemFlash # Omu
    mask: ClothingMaskSterile
    neck: ClothingCloakCmo
    outerClothing: ClothingOuterCoatLabCmo
    gloves: ClothingHandsGlovesNitrile
