// SPDX-License-Identifier: MIT

using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.Shuttles.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class IFFConsoleWindow : FancyWindow,
    IComputerWindow<IFFConsoleBoundUserInterfaceState>
{
    private readonly ButtonGroup _showIFFButtonGroup = new();
    public event Action<bool>? ShowIFF;

    // CorvaxGoob-IIF-Improves-Start
    public event Action<Color, string>? ApplyRadarSettings; 

    private string? _currentGridName;
    private Color _currentColor = Color.Gold;
    // CorvaxGoob-IIF-End

    public IFFConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        ShowIFFOffButton.Group = _showIFFButtonGroup;
        ShowIFFOnButton.Group = _showIFFButtonGroup;
        ShowIFFOnButton.OnPressed += args => ShowIFFPressed(true);
        ShowIFFOffButton.OnPressed += args => ShowIFFPressed(false);
        ApplySettings.OnPressed += args => ApplySettingsPressed(ColorPicker.Color, ShuttleName.Text); // CorvaxGoob-IIF-Improves
    }

    private void ShowIFFPressed(bool pressed)
    {
        ShowIFF?.Invoke(pressed);
    }

    // CorvaxGoob-IIF-Improves-Start
    private void ApplySettingsPressed(Color newColor, string newGridName)
    {
        if (newColor != _currentColor || newGridName != _currentGridName)
        {
            _currentColor = newColor;
            _currentGridName = newGridName;

            ApplyRadarSettings?.Invoke(newColor, newGridName);
        }
    }
    // CorvaxGoob-IIF-Improves-End
    public void UpdateState(IFFConsoleBoundUserInterfaceState state)
    {
        if ((state.AllowedFlags & IFFFlags.HideLabel) != 0x0 || (state.AllowedFlags & IFFFlags.Hide) != 0x0)
        {
            ShowIFFOffButton.Disabled = false;
            ShowIFFOnButton.Disabled = false;

            if ((state.Flags & IFFFlags.HideLabel) != 0x0 || (state.Flags & IFFFlags.Hide) != 0x0)
            {
                ShowIFFOffButton.Pressed = true;
            }
            else
            {
                ShowIFFOnButton.Pressed = true;
            }
        }
        else
        {
            ShowIFFOffButton.Disabled = true;
            ShowIFFOnButton.Disabled = true;
        }

        // CorvaxGoob-IIF-Improves-Start
        if (state.Name is not null)
            ShuttleName.Text = state.Name;

        ColorPicker.Color = state.Color;
        // CorvaxGoob-IIF-Improves-End
    }
}
