// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Humanoid;
using Content.Client.Message;
using Content.Client.Station;
using Content.Client.UserInterface.Controls;
using Content.Shared.Access.Systems;
using Content.Shared.Administration;
using Content.Shared.CriminalRecords;
using Content.Shared.Dataset;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Security;
using Content.Shared.StationRecords;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;
using Robust.Shared.Utility;
using System.Linq;
using System.Numerics;

namespace Content.Client.CriminalRecords;

// TODO: dedupe shitcode from general records theres a lot
[GenerateTypedNameReferences]
public sealed partial class CriminalRecordsConsoleWindow : FancyWindow
{
    private readonly IPlayerManager _player;
    private readonly IPrototypeManager _proto;
    private readonly IRobustRandom _random;
    private readonly AccessReaderSystem _accessReader;
    [Dependency] private readonly IEntityManager _entManager = default!;
    private readonly SpriteSystem _spriteSystem;

    private readonly HumanoidAppearanceSystem _humanoidAppearance; // CorvaxGoob-SecurityFeatures

    public readonly EntityUid Console;

    private EntityUid? _previewEntity; // CorvaxGoob-SecurityFeatures

    private static readonly ProtoId<LocalizedDatasetPrototype> ReasonPlaceholders = "CriminalRecordsWantedReasonPlaceholders";

    public Action<uint?>? OnKeySelected;
    public Action<StationRecordFilterType, string>? OnFiltersChanged;
    public Action<SecurityStatus>? OnStatusSelected;
    public Action<uint>? OnCheckStatus;
    public Action<CriminalRecord, bool, bool>? OnHistoryUpdated;
    public Action? OnHistoryClosed;
    public Action<SecurityStatus, string>? OnDialogConfirmed;
    public Action<string, int, bool>? OnDialogDetainedConfirmed; // CorvaxGoob-SecurityFeatures

    public Action<SecurityStatus>? OnStatusFilterPressed;
    private uint _maxLength;
    private bool _access;
    private uint? _selectedKey;
    private CriminalRecord? _selectedRecord;

    private DialogWindow? _reasonDialog;

    private StationRecordFilterType _currentFilterType;

    private SecurityStatus _currentCrewListFilter;

    private Direction _previewRotation = Direction.North; // CorvaxGoob-SecurityFeatures


    public CriminalRecordsConsoleWindow(EntityUid console, uint maxLength, IPlayerManager playerManager, IPrototypeManager prototypeManager, IRobustRandom robustRandom, AccessReaderSystem accessReader)
    {
        RobustXamlLoader.Load(this);

        Console = console;
        _player = playerManager;
        _proto = prototypeManager;
        _random = robustRandom;
        _accessReader = accessReader;
        IoCManager.InjectDependencies(this);
        _spriteSystem = _entManager.System<SpriteSystem>();
        _humanoidAppearance = _entManager.System<HumanoidAppearanceSystem>(); // CorvaxGoob-SecurityFeatures

        _maxLength = maxLength;
        _currentFilterType = StationRecordFilterType.Name;

        _currentCrewListFilter = SecurityStatus.None;

        OpenCentered();

        foreach (var item in Enum.GetValues<StationRecordFilterType>())
        {
            FilterType.AddItem(GetTypeFilterLocals(item), (int)item);
        }

        foreach (var status in Enum.GetValues<SecurityStatus>())
        {
            AddStatusSelect(status);
        }

        //Populate status to filter crew list
        foreach (var item in Enum.GetValues<SecurityStatus>())
        {
            CrewListFilter.AddItem(GetCrewListFilterLocals(item), (int)item);
        }

        OnClose += () => _reasonDialog?.Close();

        RecordListing.OnItemSelected += args =>
        {
            if (RecordListing[args.ItemIndex].Metadata is not uint cast)
                return;

            OnKeySelected?.Invoke(cast);
        };

        RecordListing.OnItemDeselected += _ =>
        {
            OnKeySelected?.Invoke(null);
        };

        FilterType.OnItemSelected += eventArgs =>
        {
            var type = (StationRecordFilterType)eventArgs.Id;

            if (_currentFilterType != type)
            {
                _currentFilterType = type;
                FilterListingOfRecords(FilterText.Text);
            }
        };

        //Select Status to filter crew
        CrewListFilter.OnItemSelected += eventArgs =>
        {
            var type = (SecurityStatus)eventArgs.Id;

            if (_currentCrewListFilter != type)
            {
                _currentCrewListFilter = type;

                StatusFilterPressed(type);

            }
        };

        FilterText.OnTextEntered += args =>
        {
            FilterListingOfRecords(args.Text);
        };

        StatusOptionButton.OnItemSelected += args =>
        {
            SetStatus((SecurityStatus)args.Id);
        };

        HistoryButton.OnPressed += _ =>
        {
            if (_selectedRecord is { } record)
                OnHistoryUpdated?.Invoke(record, _access, true);
        };

        // CorvaxGoob-SecurityFeatures-Start
        SpriteRotateLeft.OnPressed += _ =>
        {
            _previewRotation = _previewRotation.TurnCw();
            SetPreviewRotation(_previewRotation);
        };

        SpriteRotateRight.OnPressed += _ =>
        {
            _previewRotation = _previewRotation.TurnCcw();
            SetPreviewRotation(_previewRotation);
        };
        // CorvaxGoob-SecurityFeatures-End
    }

    public void StatusFilterPressed(SecurityStatus statusSelected)
    {
        OnStatusFilterPressed?.Invoke(statusSelected);
    }

    public void UpdateState(CriminalRecordsConsoleState state)
    {
        if (state.Filter != null)
        {
            if (state.Filter.Type != _currentFilterType)
            {
                _currentFilterType = state.Filter.Type;
            }

            if (state.Filter.Value != FilterText.Text)
            {
                FilterText.Text = state.Filter.Value;
            }
        }

        if (state.FilterStatus != _currentCrewListFilter)
        {
            _currentCrewListFilter = state.FilterStatus;
        }

        _selectedKey = state.SelectedKey;
        FilterType.SelectId((int)_currentFilterType);
        CrewListFilter.SelectId((int)_currentCrewListFilter);
        NoRecords.Visible = state.RecordListing == null || state.RecordListing.Count == 0;
        PopulateRecordListing(state.RecordListing);

        // set up the selected person's record
        var selected = _selectedKey != null;

        PersonContainer.Visible = selected;
        RecordUnselected.Visible = !selected;

        // CorvaxGoob-SecurityFeatures-Start
        SpriteView.Visible = selected;
        NoRecordSelectedLabel.Visible = !selected;

        SpriteRotateRight.Visible = selected;
        SpriteRotateLeft.Visible = selected;
        SpriteRotateSeparator.Visible = selected;
        // CorvaxGoob-SecurityFeatures-End

        _access = _player.LocalSession?.AttachedEntity is {} player
            && _accessReader.IsAllowed(player, Console);

        // hide access-required editing parts when no access
        var editing = _access && selected;
        StatusOptionButton.Disabled = !editing;

        if (state is { CriminalRecord: not null, StationRecord: not null })
        {
            PopulateRecordContainer(state.StationRecord, state.CriminalRecord);
            OnHistoryUpdated?.Invoke(state.CriminalRecord, _access, false);
            _selectedRecord = state.CriminalRecord;
        }
        else
        {
            _selectedRecord = null;
            OnHistoryClosed?.Invoke();
        }
    }

    private void PopulateRecordListing(Dictionary<uint, string>? listing)
    {
        if (listing == null)
        {
            RecordListing.Clear();
            return;
        }

        var entries = listing.Select(i => new ItemList.Item(RecordListing)
        {
            Text = i.Value,
            Metadata = i.Key
        }).ToList();
        entries.Sort((a, b) => string.Compare(a.Text, b.Text, StringComparison.Ordinal));
        RecordListing.SetItems(entries, (a,b) => string.Compare(a.Text, b.Text));
    }

    private void PopulateRecordContainer(GeneralStationRecord stationRecord, CriminalRecord criminalRecord)
    {
        var specifier = new SpriteSpecifier.Rsi(new ResPath("Interface/Misc/job_icons.rsi"), "Unknown");
        var na = Loc.GetString("generic-not-available-shorthand");
        PersonName.Text = stationRecord.Name;
        PersonJob.Text = stationRecord.JobTitle ?? na;

        // Job icon
        if (_proto.TryIndex<JobIconPrototype>(stationRecord.JobIcon, out var proto))
        {
            PersonJobIcon.Texture = _spriteSystem.Frame0(proto.Icon);
        }

        // CorvaxGoob-SecurityFeatures-Start
        if (criminalRecord.History.Count > 0)
        {
            EntriesContainer.RemoveAllChildren();

            // Heading
            var historyRecordHeadTime = new RichTextLabel
            {
                HorizontalAlignment = HAlignment.Center,
            };
            historyRecordHeadTime.SetMarkup(Loc.GetString("Время"));
            EntriesContainer.AddChild(historyRecordHeadTime);

            var historyRecordHeadCrime = new RichTextLabel
            {
                HorizontalAlignment = HAlignment.Center,
            };
            historyRecordHeadCrime.SetMarkup(Loc.GetString("Преступление"));
            EntriesContainer.AddChild(historyRecordHeadCrime);

            var historyRecordHeadInitiator = new RichTextLabel
            {
                HorizontalAlignment = HAlignment.Center,
            };
            historyRecordHeadInitiator.SetMarkup(Loc.GetString("Инициатор"));
            EntriesContainer.AddChild(historyRecordHeadInitiator);
            // Heading-End

            criminalRecord.History.Reverse();
            var currentRecordNum = 0;

            foreach (var record in criminalRecord.History)
            {
                if (currentRecordNum >= 6)
                    break;

                var historyRecordTime = new RichTextLabel
                {
                    Margin = new Thickness(0, 0, 10, 0)
                };
                historyRecordTime.Text = record.AddTime.ToString(@"hh\:mm\:ss");

                var historyRecordCrime = new RichTextLabel
                {
                    Margin = new Thickness(0, 0, 10, 0)
                };
                historyRecordCrime.Text = record.Crime;

                var historyRecordInitiator = new RichTextLabel();
                historyRecordInitiator.Text = record.InitiatorName;

                EntriesContainer.AddChild(historyRecordTime);
                EntriesContainer.AddChild(historyRecordCrime);
                EntriesContainer.AddChild(historyRecordInitiator);
                currentRecordNum++;
            }
            criminalRecord.History.Reverse();
        }
        // CorvaxGoob-SecurityFeatures-End


        PersonPrints.Text = stationRecord.Fingerprint ??  Loc.GetString("generic-not-available-shorthand");
        PersonDna.Text = stationRecord.DNA ??  Loc.GetString("generic-not-available-shorthand");

        PersonSpecies.Text = Loc.GetString(stationRecord.Species) ?? Loc.GetString("generic-not-available-shorthand"); // CorvaxGoob-SecurityFeatures

        if (criminalRecord.Status != SecurityStatus.None)
        {
            specifier = new SpriteSpecifier.Rsi(new ResPath("Interface/Misc/security_icons.rsi"),  GetStatusIcon(criminalRecord.Status));
        }
        PersonStatusTX.SetFromSpriteSpecifier(specifier);
        PersonStatusTX.DisplayRect.TextureScale = new Vector2(3f, 3f);

        // CorvaxGoob-SecurityFeatures
        if (criminalRecord.InitiatorName is { } initiator)
        {
            var message = FormattedMessage.FromMarkupOrThrow(Loc.GetString($"criminal-records-console-initiator"));
            message.AddText($": {initiator}");

            Initiator.SetMessage(message);
            Initiator.Visible = true;
        }

        UpdatePreview(stationRecord); // CorvaxGoob-SecurityFeatures

        StatusOptionButton.SelectId((int)criminalRecord.Status);
        if (criminalRecord.Reason is { } reason)
        {

            var message = FormattedMessage.FromMarkupOrThrow(Loc.GetString($"criminal-records-console-{criminalRecord.Status.ToString().ToLower()}-reason"));
            message.AddText($": {reason}");

            WantedReason.SetMessage(message);
            WantedReason.Visible = true;
        }
        else
        {
            WantedReason.Visible = false;
        }
    }

    // CorvaxGoob-SecurityFeatures
    private void UpdatePreview(GeneralStationRecord stationRecord)
    {
        if (stationRecord.Visual is null)
            return;

        var visual = stationRecord.Visual.Value;

        if (visual.SpeciesPrototype is null)
            return;

        if (_previewEntity is not null)
            _entManager.DeleteEntity(_previewEntity);

        var speciesPrototype = _proto.Index<SpeciesPrototype>(visual.SpeciesPrototype.Value);

        _previewEntity = _entManager.SpawnEntity(speciesPrototype.DollPrototype, MapCoordinates.Nullspace);
        var targetHumanoid = _entManager.EnsureComponent<HumanoidAppearanceComponent>(_previewEntity.Value);

        if (visual.SkinColor is not null)
            targetHumanoid.SkinColor = visual.SkinColor.Value;

        if (visual.Markings is not null)
            targetHumanoid.MarkingSet = visual.Markings;

        if (visual.EyesColor is not null)
            targetHumanoid.EyeColor = visual.EyesColor.Value;

        _humanoidAppearance.UpdateSprite((_previewEntity.Value, targetHumanoid, _entManager.GetComponent<SpriteComponent>(_previewEntity.Value)));

        SpriteView.SetEntity(_previewEntity.Value);
        SpriteView.Visible = true;
    }

    private void SetPreviewRotation(Direction direction)
    {
        SpriteView.OverrideDirection = (Direction) ((int) direction % 4 * 2);
    }

    private void AddStatusSelect(SecurityStatus status)
    {
        var name = Loc.GetString($"criminal-records-status-{status.ToString().ToLower()}");
        StatusOptionButton.AddItem(name, (int)status);
    }

    private void FilterListingOfRecords(string text = "")
    {
        OnFiltersChanged?.Invoke(_currentFilterType, text);
    }

    private void SetStatus(SecurityStatus status)
    {
        if (status == SecurityStatus.Wanted
            || status == SecurityStatus.Suspected
            || status == SecurityStatus.Hostile
            || status == SecurityStatus.Search // Goobstation
            || status == SecurityStatus.Dangerous // Goobstation
            || status == SecurityStatus.Demote) // Goobstation
        {
            GetReason(status);
            return;
        }

        // CorvaxGoob-SecurityFeatures
        if (status == SecurityStatus.Detained)
        {
            GetDetainedInfo();
            return;
        }

        OnStatusSelected?.Invoke(status);
    }

    private void GetReason(SecurityStatus status)
    {
        if (_reasonDialog != null)
        {
            _reasonDialog.MoveToFront();
            return;
        }

        var field = "reason";
        var title = Loc.GetString("criminal-records-status-" + status.ToString().ToLower());
        var placeholders = _proto.Index(ReasonPlaceholders);
        var placeholder = Loc.GetString("criminal-records-console-reason-placeholder", ("placeholder", Loc.GetString(_random.Pick(placeholders.Values)))); // CorvaxGoob-SecurityFeatures
        var prompt = Loc.GetString("criminal-records-console-reason");

        var entry = new QuickDialogEntry(field, QuickDialogEntryType.LongText, prompt, placeholder);
        var entries = new List<QuickDialogEntry>() { entry };
        _reasonDialog = new DialogWindow(title, entries);

        _reasonDialog.OnConfirmed += responses =>
        {
            var reason = responses[field];
            if (reason.Length < 1 || reason.Length > _maxLength)
                return;

            OnDialogConfirmed?.Invoke(status, reason);
        };

        _reasonDialog.OnClose += () => { _reasonDialog = null; };
    }

    // CorvaxGoob-SecurityFeatures
    private void GetDetainedInfo()
    {
        if (_reasonDialog != null)
        {
            _reasonDialog.MoveToFront();
            return;
        }

        var articleField = "article";
        var durationField = "duration";

        var title = Loc.GetString("criminal-records-status-detained");

        var entryArticles = new QuickDialogEntry(articleField, QuickDialogEntryType.LongText, Loc.GetString("criminal-records-console-articles"), Loc.GetString("criminal-records-console-articles-placeholder"));
        var entryDuration = new QuickDialogEntry(durationField, QuickDialogEntryType.LongText, Loc.GetString("criminal-records-console-duration"), Loc.GetString("criminal-records-console-duration-placeholder"));
        var entries = new List<QuickDialogEntry>() { entryArticles, entryDuration };
        _reasonDialog = new DialogWindow(title, entries, true, true, true, Loc.GetString("criminal-records-console-print"));

        _reasonDialog.OnConfirmed += responses =>
        {
            var articles = responses[articleField];
            var duration = responses[durationField];

            if (articles.Length < 1 || articles.Length > 256)
                return;

            if (!int.TryParse(duration, out var durationInt))
                return;

            OnDialogDetainedConfirmed?.Invoke(articles, durationInt, _reasonDialog.CheckBox.Pressed);
        };

        _reasonDialog.OnClose += () => { _reasonDialog = null; };
    }
    private string GetStatusIcon(SecurityStatus status)
    {
        return status switch
        {
            SecurityStatus.Paroled => "hud_paroled",
            SecurityStatus.Wanted => "hud_wanted",
            SecurityStatus.Detained => "hud_incarcerated",
            SecurityStatus.Discharged => "hud_discharged",
            SecurityStatus.Suspected => "hud_suspected",
            SecurityStatus.Hostile => "hud_hostile",
            SecurityStatus.Eliminated => "hud_eliminated",
            SecurityStatus.Search => "hud_search", // Goobstation
            SecurityStatus.Perma => "hud_perma",  // Goobstation
            SecurityStatus.Dangerous => "hud_dangerous",// Goobstation
            SecurityStatus.Demote => "hud_demote", // Goobstation
            _ => "SecurityIconNone"
        };
    }
    private string GetTypeFilterLocals(StationRecordFilterType type)
    {
        return Loc.GetString($"criminal-records-{type.ToString().ToLower()}-filter");
    }

    private string GetCrewListFilterLocals(SecurityStatus type)
    {
        string result;

        // If "NONE" override to "show all"
        if (type == SecurityStatus.None)
        {
            result = Loc.GetString("criminal-records-console-show-all");
        }
        else
        {
            result = Loc.GetString($"criminal-records-status-{type.ToString().ToLower()}");
        }

        return result;
    }
}
