// SPDX-License-Identifier: MIT

using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Content.Shared.CriminalRecords;
using Content.Shared.CriminalRecords.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.CriminalRecords;

/// <summary>
/// Window opened when Crime History button is pressed
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CrimeHistoryWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!; // CorvaxGoob-SecurityFeatures
    [Dependency] private readonly IGameTiming _timing = default!; // CorvaxGoob-SecurityFeatures

    public Action<string>? OnAddHistory;
    public Action<uint>? OnDeleteHistory;
    public Action<uint>? OnPrint; // CorvaxGoob-SecurityFeatures

    private uint _maxLength;
    private uint? _index;
    private DialogWindow? _dialog;

    private CriminalRecordsConsoleComponent? _component; // CorvaxGoob-SecurityFeatures

    public CrimeHistoryWindow(uint maxLength, EntityUid owner) // CorvaxGoob-SecurityFeatures : добавлен арг owner
    {
        RobustXamlLoader.Load(this);

        _maxLength = maxLength;

        _entMan.TryGetComponent(owner, out _component); // CorvaxGoob-SecurityFeatures

        OnClose += () =>
        {
            _dialog?.Close();
            // deselect so when reopening the window it doesnt try to use invalid index
            _index = null;
        };

        AddButton.OnPressed += _ =>
        {
            if (_dialog != null)
            {
                _dialog.MoveToFront();
                return;
            }

            var field = "line";
            var prompt = Loc.GetString("criminal-records-console-reason");
            var placeholder = Loc.GetString("criminal-records-history-placeholder");
            var entry = new QuickDialogEntry(field, QuickDialogEntryType.LongText, prompt, placeholder);
            var entries = new List<QuickDialogEntry> { entry };
            _dialog = new DialogWindow(Title!, entries);

            _dialog.OnConfirmed += responses =>
            {
                var line = responses[field];
                if (line.Length < 1 || line.Length > _maxLength)
                    return;

                OnAddHistory?.Invoke(line);
                // adding deselects so prevent deleting yeah
                _index = null;
                DeleteButton.Disabled = true;
                PrintButton.Disabled = true; // CorvaxGoob-SecurityFeatures
            };

            // prevent MoveToFront being called on a closed window and double closing
            _dialog.OnClose += () => { _dialog = null; };
        };
        DeleteButton.OnPressed += _ => 
        {
            if (_index is not {} index)
                return;

            OnDeleteHistory?.Invoke(index);
            // prevent total spam wiping
            History.ClearSelected();
            _index = null;
            DeleteButton.Disabled = true;
            PrintButton.Disabled = true; // CorvaxGoob-SecurityFeatures
        };

        // CorvaxGoob-SecurityFeatures
        PrintButton.OnPressed += _ =>
        {
            if (_index is not {} index)
                return;

            OnPrint?.Invoke(index);
        };

        History.OnItemSelected += args =>
        {
            _index = (uint) args.ItemIndex;
            DeleteButton.Disabled = false;
            PrintButton.Disabled = false; // CorvaxGoob-SecurityFeatures
        };
        History.OnItemDeselected += args =>
        {
            _index = null;
            DeleteButton.Disabled = true;
            PrintButton.Disabled = true;
        };
    }

    // CorvaxGoob-SecurityFeatures
    protected override void FrameUpdate(FrameEventArgs args)
    {
        PrintButton.Disabled = _component?.NextPrintTime >= _timing.CurTime || _index is  null ? true : false;
    }

    public void UpdateHistory(CriminalRecord record, bool access)
    {
        History.Clear();
        Editing.Visible = access;

        NoHistory.Visible = record.History.Count == 0;

        foreach (var entry in record.History)
        {
            var time = entry.AddTime;
            var line = $"{time.Hours:00}:{time.Minutes:00}:{time.Seconds:00} - {entry.Crime}";
            History.AddItem(line);
        }

        // deselect if something goes wrong
        if (_index is {} index && record.History.Count >= index)
            _index = null;
    }
}
