# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: Scientist
  name: job-name-scientist
  description: job-description-scientist
  playTimeTracker: JobScientist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 2.5h
  startingGear: ScientistGear
  icon: "JobIconScientist"
  supervisors: job-supervisors-rd
  #goobcoins: 20 #Goob content Corvax-Goob-coins
  skills: # CorvaxGoob-Skills
  - AdvancedBuilding
  guides: [ Science ] # goobstation
  access:
  - Research
  - Maintenance

- type: startingGear
  id: ScientistGear
  equipment:
    ears: ClothingHeadsetScience
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: ScientistChameleonOutfit
  job: Scientist
  equipment:
    head: ClothingHeadBandSkull
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskGas
    neck: ClothingNeckTieSci
    outerClothing: ClothingOuterCoatRnd
    gloves: ClothingHandsGlovesLatex
