using Content.Client._CorvaxGoob.Chat;
using Content.Client.UserInterface.Controls;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._CorvaxGoob.CharacterEditor.UI;

[GenerateTypedNameReferences]
public sealed partial class HighlightProfileEditorMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;

    private readonly ChatHighlightsSystem _chatHighlights;

    public HighlightProfileEditorMenu(JobPrototype jobProto)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _chatHighlights = _entMan.System<ChatHighlightsSystem>();
        _chatHighlights.UpdateHighlights();

        HelpButton.ToolTip = Loc.GetString("highlights-tip");
        HelpButton.Visible = true;

        SetEditorData(jobProto);
    }
    private void SetEditorData(JobPrototype jobProto)
    {
        var jobKey = jobProto.Name.Replace("job-name-", "").ToLower();

        var defaultHighlights = Loc.GetString($"highlights-{jobKey}");

        MessageInput.Placeholder = new Rope.Leaf(defaultHighlights.Replace(", ", "\n").Replace(",", "\n"));

        if (_chatHighlights.TryGetSavedHighlights(jobProto.ID, out var highlights))
            MessageInput.TextRope = new Rope.Leaf(highlights.Replace(", ", "\n"));

        ConfirmButton.OnPressed += args =>
        {
            _chatHighlights.SaveHighlightsData(jobProto.ID, Rope.Collapse(MessageInput.TextRope).Replace("\n", ", ") ?? "");
            Close();
        };
    }
}
