using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._CorvaxGoob.Ghost;

[GenerateTypedNameReferences]
public sealed partial class GhostGoLobbyConfirmWindow : FancyWindow
{
    public event Action? ContinuePressed;

    public GhostGoLobbyConfirmWindow()
    {
        RobustXamlLoader.Load(this);

        WarningLabel.SetMessage(FormattedMessage.FromMarkupPermissive(Loc.GetString("ghost-go-lobby-confirm")));

        ContinueButton.OnPressed += _ =>
        {
            ContinuePressed?.Invoke();
            Close();
        };
    }
}
