// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared.Humanoid;
using Content.Shared.StationRecords;
using Content.Shared.Humanoid.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.StationRecords;

[GenerateTypedNameReferences]
public sealed partial class GeneralRecord : Control
{
    public Action<uint>? OnDeletePressed;

    [Dependency] private readonly IClipboardManager _clipboard = null!;

    public GeneralRecord(GeneralStationRecord record, bool canDelete, uint? id, IPrototypeManager prototypeManager)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // CorvaxGoob-Locale-Start
        var age = record.Age.ToString();
        var locSex = record.Sex.ToString();
        var locJob = Loc.GetString(record.JobTitle);
        var locSpecies = Loc.GetString(prototypeManager.Index<SpeciesPrototype>(record.Species).Name);

        TitleLabel.Text = record.Name;
        AgeLabel.Text = Loc.GetString("general-station-record-console-record-age", ("age", age));
        JobLabel.Text = Loc.GetString("general-station-record-console-record-title",
            ("job", locJob));
        SpeciesLabel.Text = Loc.GetString("general-station-record-console-record-species", ("species", locSpecies));

        switch (record.Sex)
        {
            case Sex.Male:
                locSex = Loc.GetString("humanoid-profile-editor-sex-male-text");
                break;
            case Sex.Female:
                locSex = Loc.GetString("humanoid-profile-editor-sex-female-text");
                break;
            default:
                locSex = Loc.GetString("humanoid-profile-editor-sex-unsexed-text");
                break;
        }

        SexLabel.Text = Loc.GetString("general-station-record-console-record-sex",
            ("gender", locSex));
        FingerprintLabel.Text = Loc.GetString("general-station-record-console-record-fingerprint",
            ("fingerprint", record.Fingerprint ?? Loc.GetString("generic-not-available-shorthand")));
        DnaLabel.Text = Loc.GetString("general-station-record-console-record-dna",
            ("dna", record.DNA ?? Loc.GetString("generic-not-available-shorthand")));

        TitleButton.OnPressed += _ => _clipboard.SetText(record.Name);
        AgeButton.OnPressed += _ => _clipboard.SetText(age);
        JobButton.OnPressed += _ => _clipboard.SetText(locJob);
        SpeciesButton.OnPressed += _ => _clipboard.SetText(locSpecies);
        SexButton.OnPressed += _ => _clipboard.SetText(locSex);
        FingerprintButton.OnPressed += _ =>
        {
            if (record.Fingerprint is not null)
                _clipboard.SetText(record.Fingerprint);
        };

        DnaButton.OnPressed += _ =>
        {
            if (record.DNA is not null)
                _clipboard.SetText(record.DNA);
        };
        // CorvaxGoob-Locale-End

        if (canDelete && id != null)
        {
            DeleteButton.Visible = true;
            DeleteButton.OnPressed += _ => OnDeletePressed?.Invoke(id.Value);
        }
    }
}
